version: "3"

services:
  blog:
    container_name: blog
    build:
      context: ${APP_PATH:-.}
      dockerfile: Dockerfile
    image: blog
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - ${APP_PATH:-.}:/web/app
